name: mad_lbm
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py=2.10.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - matplotlib-base=3.2.2
  - mrcfile=1.1.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.2.0
  - python=3.8.3
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
